fix: add success job back into ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -103,3 +103,20 @@ jobs:
           FLAKE_ITER_NIX_SYSTEM: ${{ matrix.systems.nix-system }}
         working-directory: ${{ inputs.directory }}
         run: nix run 'https://flakehub.com/f/DeterminateSystems/flake-iter/*' -- --verbose build
+
+  success:
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ always() }}
+    permissions:
+      id-token: "write"
+      contents: "read"
+
+    steps:
+      - run: "true"
+      - run: |
+          echo "A dependent in the build matrix failed."
+          exit 1
+        if: |
+          contains(needs.*.result, 'failure') ||
+          contains(needs.*.result, 'cancelled')
